// data: [{
//         id: 0,
//         label: '网站',
//         editble: false,
//         sectionName: '',
//         btnAdd: '添加',
//         btnRename: '重命名',
//         children: [{
//           id: 0,
//           label: '科技',
//           editble: false,
//           sectionName: '',
//           btnAdd: '添加',
//           btnRename: '重命名',
//           children: [{
//             id: 0,
//             label: '手机',
//             editble: false,
//             sectionName: '',
//             btnAdd: '添加',
//             btnRename: '重命名'
//           }, {
//             id: 1,
//             label: '智能手机',
//             editble: false,
//             sectionName: '',
//             btnAdd: '添加',
//             btnRename: '重命名'
//           }, {
//             id: 2,
//             label: '电脑',
//             editble: false,
//             sectionName: '',
//             btnAdd: '添加',
//             btnRename: '重命名'
//           }]}, {
//             id: 1,
//             label: '图片',
//             editble: false,
//             sectionName: '',
//             btnAdd: '添加',
//             btnRename: '重命名',
//             children: [{
//               id: 0,
//               label: '动态',
//               editble: false,
//               sectionName: '',
//               btnAdd: '添加',
//               btnRename: '重命名'
//             }, {
//               id: 1,
//               label: '风景',
//               editble: false,
//               sectionName: '',
//               btnAdd: '添加',
//               btnRename: '重命名'
//             }, {
//               id: 2,
//               label: '壁纸',
//               editble: false,
//               sectionName: '',
//               btnAdd: '添加',
//               btnRename: '重命名'
//             }]}, {
//               id: 2,
//               label: '热点',
//               editble: false,
//               sectionName: '',
//               btnAdd: '添加',
//               btnRename: '重命名',
//               children: [{
//                 id: 0,
//                 label: '推荐',
//                 editble: false,
//                 sectionName: '',
//                 btnAdd: '添加',
//                 btnRename: '重命名'
//               }]}]}]